import type { TemplateDefinition, AgentResourceLimits } from "./types";

export const DEFAULT_RESOURCE_LIMITS: AgentResourceLimits = {
  maxConcurrentTasks: 3,
  maxRetries: 3,
  timeoutMs: 30000,
  maxMemoryBytes: 100 * 1024 * 1024,
  maxContextTokens: 4096,
  maxToolCalls: 100,
  maxMcpCalls: 50,
  maxExecutionTimeMs: 300000,
};

export const TEMPLATES: TemplateDefinition[] = [
  {
    templateId: "research",
    name: "Research Employee",
    description: "Investigates requirements, analyzes data, and produces research reports.",
    version: "1.0.0",
    purpose: "Research and analysis",
    allowedSpecializationFields: ["description", "purpose", "domain", "taskConstraints", "allowedSkills", "outputSchema"],
    forbiddenFields: ["securityClassification", "resourceLimits"],
    defaultResourceLimits: DEFAULT_RESOURCE_LIMITS,
    securityClassification: "internal",
    requiredCapabilities: [],
  },
  {
    templateId: "architecture",
    name: "Architecture Employee",
    description: "Designs system structure and architecture decisions.",
    version: "1.0.0",
    purpose: "Architecture design",
    allowedSpecializationFields: ["description", "purpose", "domain", "taskConstraints", "allowedSkills", "outputSchema"],
    forbiddenFields: ["securityClassification", "resourceLimits"],
    defaultResourceLimits: DEFAULT_RESOURCE_LIMITS,
    securityClassification: "internal",
    requiredCapabilities: [],
  },
  {
    templateId: "coding",
    name: "Coding Employee",
    description: "Implements code, writes tests, and performs code reviews.",
    version: "1.0.0",
    purpose: "Code implementation",
    allowedSpecializationFields: ["description", "purpose", "domain", "taskConstraints", "allowedSkills", "outputSchema"],
    forbiddenFields: ["securityClassification", "resourceLimits"],
    defaultResourceLimits: DEFAULT_RESOURCE_LIMITS,
    securityClassification: "internal",
    requiredCapabilities: [],
  },
  {
    templateId: "testing",
    name: "Testing Employee",
    description: "Validates functionality, finds bugs, and ensures quality.",
    version: "1.0.0",
    purpose: "Testing and quality assurance",
    allowedSpecializationFields: ["description", "purpose", "domain", "taskConstraints", "allowedSkills", "outputSchema"],
    forbiddenFields: ["securityClassification", "resourceLimits"],
    defaultResourceLimits: DEFAULT_RESOURCE_LIMITS,
    securityClassification: "internal",
    requiredCapabilities: [],
  },
  {
    templateId: "security",
    name: "Security Employee",
    description: "Reviews security, validates permissions, and identifies vulnerabilities.",
    version: "1.0.0",
    purpose: "Security review and validation",
    allowedSpecializationFields: ["description", "purpose", "domain", "taskConstraints", "allowedSkills", "outputSchema"],
    forbiddenFields: ["securityClassification", "resourceLimits"],
    defaultResourceLimits: DEFAULT_RESOURCE_LIMITS,
    securityClassification: "confidential",
    requiredCapabilities: [],
  },
  {
    templateId: "review",
    name: "Review Employee",
    description: "Reviews code, architecture, and results for correctness.",
    version: "1.0.0",
    purpose: "Code and result review",
    allowedSpecializationFields: ["description", "purpose", "domain", "taskConstraints", "allowedSkills", "outputSchema"],
    forbiddenFields: ["securityClassification", "resourceLimits"],
    defaultResourceLimits: DEFAULT_RESOURCE_LIMITS,
    securityClassification: "internal",
    requiredCapabilities: [],
  },
  {
    templateId: "documentation",
    name: "Documentation Employee",
    description: "Creates and maintains project documentation.",
    version: "1.0.0",
    purpose: "Documentation",
    allowedSpecializationFields: ["description", "purpose", "domain", "taskConstraints", "allowedSkills", "outputSchema"],
    forbiddenFields: ["securityClassification", "resourceLimits"],
    defaultResourceLimits: DEFAULT_RESOURCE_LIMITS,
    securityClassification: "public",
    requiredCapabilities: [],
  },
  {
    templateId: "analytics",
    name: "Analytics Employee",
    description: "Analyzes metrics and performance data.",
    version: "1.0.0",
    purpose: "Data analytics",
    allowedSpecializationFields: ["description", "purpose", "domain", "taskConstraints", "allowedSkills", "outputSchema"],
    forbiddenFields: ["securityClassification", "resourceLimits"],
    defaultResourceLimits: DEFAULT_RESOURCE_LIMITS,
    securityClassification: "internal",
    requiredCapabilities: [],
  },
  {
    templateId: "skill",
    name: "Skill Employee",
    description: "Validates and maintains skill definitions.",
    version: "1.0.0",
    purpose: "Skill validation and maintenance",
    allowedSpecializationFields: ["description", "purpose", "domain", "taskConstraints", "allowedSkills", "outputSchema"],
    forbiddenFields: ["securityClassification", "resourceLimits"],
    defaultResourceLimits: DEFAULT_RESOURCE_LIMITS,
    securityClassification: "internal",
    requiredCapabilities: [],
  },
];

export function getTemplate(templateId: string): TemplateDefinition | undefined {
  return TEMPLATES.find(t => t.templateId === templateId);
}

export function listTemplates(): TemplateDefinition[] {
  return [...TEMPLATES];
}
